### PR TITLE
Add response body to exception for Auth failures

### PR DESCRIPTION
**Pull request by mikegrass**
Similar to #49, including the response body in the exception thrown for auth failures provides information that is helpful for debugging failed logins.

Add the response body to the VaultException thrown when an Auth method fails.

I've also fixed up a couple of issues that the build complained about:

```
> Task :javadoc
...
/Users/mgrass/src/vault-java-driver/src/main/java/com/bettercloud/vault/VaultConfig.java:216: error: @param name not found
     * @param prefixPathDepth integer number of path elements in the prefix path
              ^
...

> Task :javadoc FAILED
```

```
> Task :checkstyleMain FAILED
[ant:checkstyle] [ERROR] /Users/mgrass/src/vault-java-driver/src/main/java/com/bettercloud/vault/VaultConfig.java:212: Trailing spaces are not allowed. [RegexpSingleline]
[ant:checkstyle] [ERROR] /Users/mgrass/src/vault-java-driver/src/main/java/com/bettercloud/vault/api/Logical.java:6:8: Unused import - com.bettercloud.vault.json.JsonArray. [UnusedImports]
[ant:checkstyle] [ERROR] /Users/mgrass/src/vault-java-driver/src/main/java/com/bettercloud/vault/api/Logical.java:13:8: Unused import - java.util.ArrayList. [UnusedImports]
[ant:checkstyle] [ERROR] /Users/mgrass/src/vault-java-driver/src/main/java/com/bettercloud/vault/api/Logical.java:15:8: Unused import - java.util.List. [UnusedImports]
```

Unfortunately, it looks like compilation of tests was broken by https://github.com/BetterCloud/vault-java-driver/pull/189; based on https://github.com/BetterCloud/vault-java-driver/pull/189#issuecomment-546507585 it sounds like @steve-perkins has a fix on the way for the broken tests, so I haven't touched those.

### CODE REVIEW

**Comment by steve-perkins** [comment]
Thanks!
